pipeline {
    agent any
    stages {
        stage('Data Creation') {
            steps {
                script {
                    sh '''
                    echo "Начинаем выполнение создания данных..."
                    python3 scripts/data_creation.py
                    echo "Данные успешно созданы."
                    '''
                }
            }
        }
        stage('Data Preprocessing') {
            steps {
                script {
                    sh '''
                    echo "Начинаем предобработку данных..."
                    python3 scripts/model_preprocessing.py
                    echo "Данные успешно предобработаны."
                    '''
                }
            }
        }
        stage('Model Preparation') {
            steps {
                script {
                    sh '''
                    echo "Начинаем подготовку и обучение модели..."
                    python3 scripts/model_preparation.py
                    echo "Модель успешно подготовлена и обучена."
                    '''
                }
            }
        }
        stage('Model Testing') {
            steps {
                script {
                    sh '''
                    echo "Начинаем тестирование модели..."
                    python3 scripts/model_testing.py
                    echo "Модель успешно протестирована."
                    echo "Завершение выполнения."
                    '''
                }
            }
        }
    }
}
